# ============================================================
# Licitum — Prisma Baseline + ApiCache Migration Script
# ============================================================
# Execute este script a partir da pasta:
#   c:\Users\kacia\Downloads\licitum-saas\licitum\backend
#
# Uso: powershell -ExecutionPolicy Bypass -File prisma-baseline.ps1
# ============================================================

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$backendDir = Split-Path -Parent $MyInvocation.MyCommand.Definition

Write-Host ""
Write-Host "  =========================================" -ForegroundColor Cyan
Write-Host "  LICITUM — Prisma Baseline Migration" -ForegroundColor Cyan
Write-Host "  =========================================" -ForegroundColor Cyan
Write-Host ""

# ─── Passo 1: Remover migrations antigas que causam drift ────────────────────

$oldMigrations = @(
    "$backendDir\prisma\migrations\202605050001_init",
    "$backendDir\prisma\migrations\202605060002_align_prisma_enum_names"
)

foreach ($dir in $oldMigrations) {
    if (Test-Path $dir) {
        Remove-Item -Recurse -Force $dir
        Write-Host "  [OK] Removido: $(Split-Path -Leaf $dir)" -ForegroundColor Yellow
    } else {
        Write-Host "  [--] Ja removido: $(Split-Path -Leaf $dir)" -ForegroundColor DarkGray
    }
}

# ─── Passo 2: Garantir que a baseline migration existe ───────────────────────

$baselineDir = "$backendDir\prisma\migrations\20260509120000_init"
$baselineSql = "$baselineDir\migration.sql"
$lockFile = "$backendDir\prisma\migrations\migration_lock.toml"

if (-not (Test-Path $baselineDir)) {
    New-Item -ItemType Directory -Path $baselineDir -Force | Out-Null
    Write-Host "  [OK] Criado diretorio baseline" -ForegroundColor Green
}

if (-not (Test-Path $baselineSql)) {
    Set-Content -Path $baselineSql -Value "-- baseline migration`n"
    Write-Host "  [OK] Criado migration.sql (baseline)" -ForegroundColor Green
} else {
    Write-Host "  [OK] migration.sql ja existe" -ForegroundColor Green
}

if (-not (Test-Path $lockFile)) {
    Set-Content -Path $lockFile -Value "# Please do not edit this file manually`nprovider = `"postgresql`"`n"
    Write-Host "  [OK] Criado migration_lock.toml" -ForegroundColor Green
} else {
    Write-Host "  [OK] migration_lock.toml ja existe" -ForegroundColor Green
}

Write-Host ""
Write-Host "  ─── Estrutura de migrations ───" -ForegroundColor DarkGray
Get-ChildItem -Path "$backendDir\prisma\migrations" -Recurse | ForEach-Object {
    Write-Host "    $($_.FullName.Replace($backendDir, '.'))" -ForegroundColor DarkGray
}

# ─── Passo 3: Marcar baseline como aplicada ──────────────────────────────────

Write-Host ""
Write-Host "  [3/4] Marcando baseline como aplicada..." -ForegroundColor Cyan
try {
    & npx prisma migrate resolve --applied 20260509120000_init 2>&1
    Write-Host "  [OK] Baseline marcada como aplicada" -ForegroundColor Green
} catch {
    Write-Host "  [WARN] Erro ao marcar baseline (pode ja estar marcada): $_" -ForegroundColor Yellow
}

# ─── Passo 4: Criar migration do ApiCache ────────────────────────────────────

Write-Host ""
Write-Host "  [4/4] Criando migration add_api_cache_transparencia..." -ForegroundColor Cyan
& npx prisma migrate dev --name add_api_cache_transparencia 2>&1

# ─── Passo 5: Regenerar Prisma Client ────────────────────────────────────────

Write-Host ""
Write-Host "  [BONUS] Gerando Prisma Client..." -ForegroundColor Cyan
& npx prisma generate 2>&1

# ─── Passo 6: Instalar Bottleneck (se necessário) ───────────────────────────

$bottleneckPath = "$backendDir\node_modules\bottleneck"
if (-not (Test-Path $bottleneckPath)) {
    Write-Host ""
    Write-Host "  [BONUS] Instalando bottleneck..." -ForegroundColor Cyan
    & npm install bottleneck 2>&1
} else {
    Write-Host "  [OK] Bottleneck ja instalado" -ForegroundColor Green
}

Write-Host ""
Write-Host "  =========================================" -ForegroundColor Green
Write-Host "  CONCLUIDO! Prisma sincronizado." -ForegroundColor Green
Write-Host "  =========================================" -ForegroundColor Green
Write-Host ""
